services:
  - type: web
    name: mfxray-backend
    env: python
    rootDir: .
    buildCommand: "pip install -r mf-xray/backend/requirements.txt"
    startCommand: "cd mf-xray/backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PYTHONPATH
        value: "/opt/render/project/src/mf-xray/backend"
