"""
AI Money Mentor — Centralized Configuration
All market assumptions, tax rates, and guardrails are defined here.
No hardcoded financial constants elsewhere in the codebase.
"""

# ─── Market Return Assumptions (annualized, nominal) ────────────────────────
EQUITY_RETURN = 0.12          # 12% expected equity return (India long-term avg)
DEBT_RETURN = 0.07            # 7% expected debt/bond return
FD_RETURN = 0.065             # 6.5% fixed deposit return
BLENDED_RETURN = 0.10         # 10% blended portfolio return (default)

# ─── Inflation ──────────────────────────────────────────────────────────────
INFLATION_RATE = 0.06         # 6% CPI inflation (India avg)

# ─── Tax Rates (India FY 2025-26) ───────────────────────────────────────────
STCG_RATE = 0.20              # 20% Short-Term Capital Gains (equity, <1yr)
LTCG_RATE = 0.125             # 12.5% Long-Term Capital Gains (equity, >1yr)
LTCG_EXEMPTION = 125000       # ₹1.25L annual LTCG exemption
DEBT_FUND_TAX_RATE = 0.30     # Debt fund gains taxed at slab rate (approx 30%)

# ─── Expense Ratios ────────────────────────────────────────────────────────
DEFAULT_EXPENSE_RATIO = 0.015  # 1.5% avg active fund expense ratio
INDEX_FUND_EXPENSE = 0.002     # 0.2% index fund expense ratio

# ─── FIRE (Financial Independence, Retire Early) ───────────────────────────
SAFE_WITHDRAWAL_RATE = 0.04   # 4% rule (annual withdrawal from corpus)
DEFAULT_RETIREMENT_AGE = 60
LIFE_EXPECTANCY = 85
DEFAULT_MONTHLY_EXPENSES = 50000  # ₹50K/month as default assumption

# ─── SWP (Systematic Withdrawal Plan) ──────────────────────────────────────
SWP_RATE = 0.06               # 6% post-retirement real return

# ─── Guardrails ─────────────────────────────────────────────────────────────
DISCLAIMER = (
    "\n\n⚠️ **DISCLAIMER:** This analysis is generated by an AI system for "
    "educational and informational purposes only. It does NOT constitute "
    "financial advice from a SEBI-registered Investment Advisor (RIA). "
    "Mutual fund investments are subject to market risks. Please consult "
    "a qualified financial advisor before making any investment decisions. "
    "Past performance does not guarantee future results."
)

# ─── Agent Configuration ───────────────────────────────────────────────────
MAX_SESSION_AGE_SECONDS = 3600  # Sessions expire after 1 hour
MAX_SESSIONS = 1000             # Max concurrent sessions in memory
